### ISSUE TITLE
How to use textures?

### ISSUE THREAD

**Issue by R-N** [cowtrix/voxul#9]
I'd like to uses texture with automatic UV mapping like in minecraft grass

**Comment by cowtrix** [comment]
Hi @R-N, thanks for your interest in voxul.

I've just pushed a commit which should hopefully re-enable texture painting in the editor. See below for a screenshot: just select your texture in the picker and it will get packed into a 3D texture. Note that 3D textures are not supported on all platforms (I think webGL doesn't support it from memory).

![image](https://github.com/cowtrix/voxul/assets/5094696/2738be6c-d646-42a2-81a6-c3235d205aa6)

Make sure your voxel material is using the `Voxul\DefaultVoxel` shader and has the `SPRITESHEET` shader property enabled.

**Comment by R-N** [comment]
Thank you. Both the quick response and the framework itself.

I tried but it seems like it still doesn't use the texture. The color show just fine though. The blocks were made before setting texture and color, and then painted. That's why some are white. The rightmost block though, I added it after setting texture and color and I did not repaint it. It has the color out of the box. No errors are thrown. 

![image](https://github.com/cowtrix/voxul/assets/1442761/a743c664-1f07-4176-b944-bb3c8209d473)

I set them to various color because it did not seem to be doing anything when it was white, because the blocks are white by default and the texture doesn't apply, so it was painting white over white.

<details>
<summary>Here's the object properties</summary>

![image](https://github.com/cowtrix/voxul/assets/1442761/6d5f69eb-e75a-4473-99be-ae1e526cd21d)
![image](https://github.com/cowtrix/voxul/assets/1442761/17b08ab3-d00f-492f-88bf-9027591cc99c)
![image](https://github.com/cowtrix/voxul/assets/1442761/c4bf8d5c-9fef-4a4b-ba11-74c6c7ee5fe2)
</details>

By the way, although I don't know if it's related, clicking "Set voxels for selection (Shift + M)" throws error. If it's unrelated then it's fine, I don't use it. I don't even know what it does.

<details>
<summary>The error</summary>

```
InvalidOperationException: Collection was modified; enumeration operation may not execute.
System.Collections.Generic.Dictionary`2+Enumerator[TKey,TValue].MoveNext () (at <fb9cb1df970c4c34a7934ab4caf453a1>:0)
System.Linq.Enumerable+WhereSelectEnumerableIterator`2[TSource,TResult].MoveNext () (at <59e7b6dabdf549b88aa5b4f75038790c>:0)
Voxul.Edit.SelectTool.DrawInspectorGUI (Voxul.Edit.VoxelPainter voxelPainter) (at Assets/voxul/Scripts/Editor/Tools/SelectTool.cs:45)
Voxul.Edit.VoxelPainter.DrawSpecificGUI () (at Assets/voxul/Scripts/Editor/VoxelPainter.cs:176)
Voxul.Edit.VoxelObjectEditorBase`1[T].OnInspectorGUI () (at Assets/voxul/Scripts/Editor/VoxelObjectEditorBase.cs:62)
UnityEditor.UIElements.InspectorElement+<>c__DisplayClass72_0.<CreateInspectorElementUsingIMGUI>b__0 () (at <0be88e8ab6e346e9aff7a2ef25f50b89>:0)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr, Boolean&)
```
</details>

Environment:
- Windows 11 21H2 64-bit
- Unity 2023.1.12f1
- Build target windows
- New project, everything default

I took the textures from [here](https://github.com/BayatGames/VoxelFramework/tree/master/Assets/Textures/Tiles).

**Comment by R-N** [comment]
Oh my bad. I didn't know I had to slide the "Texture Fade" to 1. 

Okay so now it works, kinda. It's greyscale. Probably because the color is set to white. Can I have the original color?

![image](https://github.com/cowtrix/voxul/assets/1442761/561a4ccd-1e05-40a2-aaf7-2b72db1b26a0)

**Comment by R-N** [comment]
I noticed another issue that the "Override" doesn't save. I saved the scene, closed Unity, then reopen it again, and now the "Override" section is empty. 

![image](https://github.com/cowtrix/voxul/assets/1442761/5b1b849a-c3d1-4b8d-8b3d-b4ce0a3c1578)

Wait, the "Texture Fade" doesn't save either. Not sure if the color does since I left it to white.

**Comment by cowtrix** [comment]
You can alter the ShaderGraph to change how the texture is blended with the input color, right now it's done with multiply. You'd change the following: 
![image](https://github.com/cowtrix/voxul/assets/5094696/87b1e542-25a5-4969-99e8-e0df44d08922)

To save a set of voxel brush settings, create a new Voxel Brush (Create > voxul > Voxel Material Brush). It should then display in the "presets" list, if you refresh it.

**Comment by cowtrix** [comment]
Hey @R-N, was this clear? Is your issue closed? If so, can we close this?

**Comment by R-N** [comment]
Sorry I had been too busy to try it. I'll try it now

**Comment by cowtrix** [comment]
Ah yeah I understand what's going on here. Basically the uv mapping isn't being properly updated when we combine quads, that's why it works when there's only one voxel face but when they can be combined it looks stretched. I think it should be a relatively simple fix, let me have a look.

For your use case I would use Local Scaled, that means you have a 1:1 scaling to your voxel block which is what MineCraft does. I'll add looking at the other UV mapping modes.

**Comment by cowtrix** [comment]
> By the way, the material brush isn't loaded by default after I reopen the project, so I guess it's not tied to the GameObject. How do I add a block using a material brush, by code?

You can add a reference to VoxelBrushAsset in your script, and then use it to generate a voxel object. A bit of the code that does this is the `AddTool`:
```private IEnumerable<VoxelCoordinate> CreateVoxel(IEnumerable<VoxelCoordinate> coords, VoxelRenderer renderer)
		{
			foreach (var brushCoord in coords)
			{
				UnityEngine.Random.InitState(brushCoord.GetHashCode());
				if (renderer.Mesh.Voxels.AddSafe(new Voxel(brushCoord, CurrentBrush.Generate(UnityEngine.Random.value))))
				{
					yield return brushCoord;
				}
			}
			renderer.Mesh.Invalidate();
			renderer.Invalidate(true, true);
		}```
```

**Comment by cowtrix** [comment]
I had a moment to fix UV mapping, hopefully. Grab latest and give it a go.

**Comment by cowtrix** [comment]
Pushed a breaking change - i.e. you'll lose the sprites you currently have and will have to re-add them - but a change which will hopefully greatly improve the experience of managing these textures. You now have the `Spritesheet` asset which contains the references to original textures as well as the packed texture that's given to the shader. One will be made by default within your VoxelManager, but you can also have per-renderer spritesheets. The picker in the painter now has a dropdown of all textures currently within the spritesheet, as well as an object field to add new ones.

**Comment by R-N** [comment]
Sorry I haven't tried the code yet.

The UV mapping is now consistent, thank you. The split faces are due to two separate voxel renderers, don't worry about them.
![image](https://github.com/cowtrix/voxul/assets/1442761/5e78f9dd-4e2a-461a-9fa0-791fb9cbdeed)

However, this change seems to break the brush? I can't set the textures. Setting from the painter works fine. 
![image](https://github.com/cowtrix/voxul/assets/1442761/ddf2474a-83ed-4371-841b-ce08c73f6b91)

However the texture dropdown doesn't seem to work. I think it's populated by remembering textures I've set previously, but choosing from the dropdown doesn't change the texture. Not that I mind, I can just use the old picker. 

The new Sprite asset confuse me. What's the difference between Albedo and Material texture?  How do I use it? The spritesheet override? I set it and it broke the voxels, they're now all white. I tried rebuilding them but it's still white, despite the brush showing textures. Also, the brush doesn't respect the texture override I've set now. 

![image](https://github.com/cowtrix/voxul/assets/1442761/9b39e006-16b9-4c52-af1a-672d9d5f109c)
![image](https://github.com/cowtrix/voxul/assets/1442761/ef1f6faa-9684-4b5d-ae4b-584a8aebb43d)
![image](https://github.com/cowtrix/voxul/assets/1442761/f5f3b91b-5b2e-4d97-8568-f9634a873273)

I noticed that the dropdown is now populated by textures from the Spritesheet. However, selecting from the dropdown doesn't work so I selected from the old picker. Might this be the cause?

**Comment by R-N** [comment]
I tried the code. It works, but throws an error.

<details>
<summary>The error</summary>

```
Destroying assets is not permitted to avoid data loss.
If you really want to remove an asset use DestroyImmediate (theObject, true);
UnityEngine.Object:Destroy (UnityEngine.Object)
Voxul.Utilities.Util:SafeDestroy (UnityEngine.Object) (at Assets/voxul/Scripts/Utilities/Util.cs:226)
Voxul.Meshing.VoxelMeshWorker:Complete (System.Guid) (at Assets/voxul/Scripts/Meshing/VoxelMeshWorker.cs:262)
Voxul.Meshing.VoxelMeshWorker/<>c__DisplayClass15_0:<GenerateMesh>b__0 () (at Assets/voxul/Scripts/Meshing/VoxelMeshWorker.cs:201)
Voxul.Utilities.UnityMainThreadDispatcher:Execute () (at Assets/voxul/Scripts/Utilities/UnityMainThreadDispatcher.cs:99)
UnityEditor.EditorApplication:Internal_CallUpdateFunctions ()
```
</details>

I think it's trying to destroy the VoxelMesh, but it's an asset I created from the editor. 

Also, I have some question. 

- What does VoxelBrush.Generate do? What's its float parameter? In your snippet, you used a random number, why?
- What's the difference between the two Invalidate functions?

**Comment by R-N** [comment]
Oh, right. I noticed that the sliders in the brush are range sliders. What's the range for? Random sample space?
